### PR TITLE
Adding adjoint and 2-adjoint equivalences

### PR DESCRIPTION
**Pull request by RyanSandford**
adj.lean contains definitions and theorems regarding half adjoint equivalences which formalize 
4.2.3, 4.2.7, 4.2.9, 4.2.10, 4.2.12, and 4.2.13 from section 4.2 of the HoTT Book.
2adj.lean contains definitions and theorems regarding half 2-adjoint equivalences which formalize analogous theorems to that of 4.2.3, 4.2.12, 4.2.13 from section 4.2 of the HoTT Book.

### CODE REVIEW

**Comment by fpvandoorn** [comment]
Thanks for the PR. This is a nice formalization. 
If you want this merged, it might make sense to incorporate it a bit more into the library. In the file `types.adj` there are a bunch of lemmas that are also in `types.equiv`.

**Comment by RyanSandford** [comment]
@fpvandoorn Thank you for the quick reply. We don’t know how to use protected definitions and theorems from types.equiv at this time,  previous attempts to call them have failed, if you could let us know how to do that, we could certainly make those changes right away.

**Comment by fpvandoorn** [comment]
Most results are not `protected`. `protected` means that the name will not be shortened (when you open a namespace), so if you want to use https://github.com/gebner/hott3/blob/64a297c4c1effa4886abcdc08dd88824a7b27455/src/hott/types/equiv.lean#L61 you have to write `is_equiv.sigma_char`.

**Comment by RyanSandford** [comment]
@fpvandoorn Thank you for your replies, they've been helpful! My apologies for the delay in making the requested changes. My research partner Daniel has submitted a Pull Request with the suggested changes, including removing lemmas already proved in types.adj. 

If you get a spare moment in the upcoming weeks it would mean a lot to us if you could look over his request and let us know if there anything we can improve upon.

**Comment by fpvandoorn** [comment]
Closing in favor of #16.

**Pull request closed without merging**
